[package]
name = "sqlite-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.45"
clap = "3.0.0-beta.2"
cli-table = "0.4.6"
colored = "2.0.0"
itertools = "0.10.1"
rusqlite = { version = "0.26.1", features = ["column_decltype"] }
rustyline = "9.0.0"
sqlformat = "0.1.8"
sqlparser = "0.12.0"

[features]
